FROM debian:buster

RUN apt-get update && apt install -y\
	curl\
	nodejs

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get install -y nodejs

COPY ./five-stars /five-stars

COPY ./script_installation.sh /

WORKDIR /five-stars


ENTRYPOINT ["bash", "../script_installation.sh"]
